### ISSUE TITLE
Error Running Weed Detection Notebook

### ISSUE THREAD

**Issue by exrobotdad** [microsoft/farmvibes-ai#100]
Hello there.  I'm trying to run the weed detection workflow via the sample notebook and it fails instantly.  From what I can see in the logs it is able to download the input files, but fails on a subtask with the error below.  Even with the latest release it still fails.  Any help will be appreciated.

![image](https://github.com/microsoft/farmvibes-ai/assets/132970576/3f04d026-3709-40cc-93cf-2ce4295c6065)

```
"app_id": "terravibes-orchestrator", "instance": "terravibes-orchestrator-b5755cff8-d6nwz", "level": "ERROR", "msg": "Failed to run workflow weed_detection. (run id: 09df0431-b092-4bea-8db3-e62167c88ab5)", "scope": "vibe_server.workflow.runner.runner.RemoteWorkflowRunner", "time": "2023-05-19 16:22:23,544", "type": "log", "ver": "dev"}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/workflow/runner/runner.py", line 142, in sub_run
    self.update_state(
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 256, in __call__
    if self.update_cache_for(op, change, reason, **kwargs):
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 227, in update_cache_for
    return self.update_subtask_submission_change(op, cast(int, subtask_idx))
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 173, in update_subtask_submission_change
    opcache["subtasks"][subtask_idx] = details
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/workflow/runner/runner.py", line 258, in _monitor_futures
    result = op_future.result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/workflow/runner/runner.py", line 159, in sub_run
    self.update_state(
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 256, in __call__
    if self.update_cache_for(op, change, reason, **kwargs):
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 233, in update_cache_for
    return self.update_subtask_failure_change(op, reason, cast(int, subtask_idx))
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 195, in update_subtask_failure_change
    opcache = self.cache[op]["subtasks"][subtask_idx]
TypeError: 'NoneType' object is not subscriptable
{"app_id": "terravibes-orchestrator", "instance": "terravibes-orchestrator-b5755cff8-d6nwz", "level": "ERROR", "msg": "Failed to run workflow weed_detection (run id: 09df0431-b092-4bea-8db3-e62167c88ab5)", "scope": "vibe_server.workflow.runner.runner.RemoteWorkflowRunner", "time": "2023-05-19 16:22:23,571", "type": "log", "ver": "dev"}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/workflow/runner/runner.py", line 142, in sub_run
    self.update_state(
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 256, in __call__
    if self.update_cache_for(op, change, reason, **kwargs):
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 227, in update_cache_for
    return self.update_subtask_submission_change(op, cast(int, subtask_idx))
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 173, in update_subtask_submission_change
    opcache["subtasks"][subtask_idx] = details
TypeError: 'NoneType' object does not support item assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/workflow/runner/runner.py", line 334, in run
    output = self._run_graph(self.io_mapper.map_input(input_items), run_id)
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/workflow/runner/runner.py", line 319, in _run_graph
    output = self._run_graph_impl(input, run_id)
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/workflow/runner/runner.py", line 212, in _run_graph_impl
    self._run_ops(ops, run_id)
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/workflow/runner/remote_runner.py", line 201, in _run_ops
    super()._run_ops(ops, run_id)
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/workflow/runner/runner.py", line 234, in _run_ops
    self._monitor_futures(op_futures, op_parallelism, run_id)
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/workflow/runner/runner.py", line 258, in _monitor_futures
    result = op_future.result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/workflow/runner/runner.py", line 159, in sub_run
    self.update_state(
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 256, in __call__
    if self.update_cache_for(op, change, reason, **kwargs):
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 233, in update_cache_for
    return self.update_subtask_failure_change(op, reason, cast(int, subtask_idx))
  File "/opt/conda/lib/python3.8/site-packages/vibe_server/orchestrator.py", line 195, in update_subtask_failure_change
    opcache = self.cache[op]["subtasks"][subtask_idx]
TypeError: 'NoneType' object is not subscriptable
```

Log files are below.
[terravibes-cache.log](https://github.com/microsoft/farmvibes-ai/files/11518869/terravibes-cache.log)
[terravibes-orchestrator.log](https://github.com/microsoft/farmvibes-ai/files/11518870/terravibes-orchestrator.log)
[terravibes-rest-api.log](https://github.com/microsoft/farmvibes-ai/files/11518871/terravibes-rest-api.log)
[terravibes-worker-5fd9f7b6bf-f97np.log](https://github.com/microsoft/farmvibes-ai/files/11518872/terravibes-worker-5fd9f7b6bf-f97np.log)
[terravibes-worker-864cd74bc8-rvcld.log](https://github.com/microsoft/farmvibes-ai/files/11518873/terravibes-worker-864cd74bc8-rvcld.log)

**Comment by rafaspadilha** [comment]
Hi, @exrobotdad. Thank you for using FarmVibes and raising this issue.
We have seen this issue internally when someone is running mismatching version of FarmVibes.AI cluster and `vibe_core` library. 

Please, make sure you do a `git pull` (which I assume you'd done, as you said you are running the latest release) and `bash farmvibes-ai.sh update`, which should update the cluster images and also the `vibe_core` library.

Let me know if that solves your issue.

**Comment by exrobotdad** [comment]
Hi @rafaspadilha .  Thank you for your response about this issue.  I re-ran the `git pull ` and there was nothing new to pull down.  I ran the `bash farmvibes-ai.sh update` again and it ran through the update process again. There was an error about failing to run terraform init.  I have attached the std out from the update.

Looking a bit under the hood, I see that the pods are running image tagged 2023.04.17.  Should they be running a newer image?
Another thing I should mention is that I am able to run other workflows such as the heatmap and helloworld successfully. 

Thank you!
[updatelog.txt](https://github.com/microsoft/farmvibes-ai/files/11653874/updatelog.txt)

**Comment by rafaspadilha** [comment]
Hey, @exrobotdad. A few releases back, we have introduced TerraForm to deploy services in our cluster, but it seems that the update is failing because there isn't any TerraForm state in your environment. 

Could I ask you to recreate your cluster, instead of updating it?
A `bash farmvibes-ai.sh destroy`, followed by a `bash farmvibes-ai.sh setup` should do the trick.

Let me know if that fix your issue.

**Comment by renatolfc** [comment]
To complement @rafaspadilha's comment, `2023.04.17` is not the latest version. When you run `update`, you are downloading the correct version of the images (`2023.05.18`), but terraform is refusing to upgrade it.

That's a bug in the `farmvibes-ai.sh` script.

Rafael's solution should do the trick, as he mentioned, but if you think that's not a solution, you're welcome to open another issue for us to track the underlying bug in the script.

(Notice that we are working on a rewrite of the script to Python, and we think that'll be the ultimate fix for that bug.)

**Comment by exrobotdad** [comment]
thank you both @renatolfc and @rafaspadilha for your help.  Destroying and rebuilding seems to have fixed that issue with the weed_detection workflow failing immediately.  I will test further tomorrow.
