### ISSUE TITLE
'Temporary failure in name resolution' when attempting to run workflows from an Azure ML compute instance

### ISSUE THREAD

**Issue by NicholasBerryman** [microsoft/farmvibes-ai#17]
My organisation has set up a compute instance on Azure ML Studio, and the quickstart guide was followed to set up Farmvibes on it.

When attempting to run any workflows (including the example helloworld workflow), the run fails.
Upon inspecting the failure, the attached error appears.

The error persists after restarting the instance and after restarting the farmvibes cluster.

```
{'hello': RunDetails(start_time=datetime.datetime(2022, 11, 15, 4, 41, 35, 737941), end_time=datetime.datetime(2022, 11, 15, 4, 42, 35, 895460), reason='RuntimeError: status=<OpStatusType.failed: \'failed\'> ename="<class \'RuntimeError\'>" evalue=\'Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/conda/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/opt/conda/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/opt/conda/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 129, in run_op
    return factory.build(spec).run(input)
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/ops.py", line 221, in run
    items_out = self.storage.store(self.name, run_id, stac_results, cache_info)
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/storage/local_storage.py", line 137, in store
    self._catalog_cleanup(catalog)
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/storage/local_storage.py", line 113, in _catalog_cleanup
    catalog.validate_all()
  File "/opt/conda/lib/python3.8/site-packages/pystac/catalog.py", line 874, in validate_all
    self.validate()
  File "/opt/conda/lib/python3.8/site-packages/pystac/stac_object.py", line 54, in validate
    return pystac.validation.validate(self)
  File "/opt/conda/lib/python3.8/site-packages/pystac/validation/__init__.py", line 31, in validate
    return validate_dict(
  File "/opt/conda/lib/python3.8/site-packages/pystac/validation/__init__.py", line 102, in validate_dict
    return RegisteredValidator.get_validator().validate(
  File "/opt/conda/lib/python3.8/site-packages/pystac/validation/stac_validator.py", line 101, in validate
    core_result = self.validate_core(
  File "/opt/conda/lib/python3.8/site-packages/pystac/validation/stac_validator.py", line 217, in validate_core
    self._validate_from_uri(stac_dict, schema_uri)
  File "/opt/conda/lib/python3.8/site-packages/pystac/validation/stac_validator.py", line 162, in _validate_from_uri
    schema, resolver = self.get_schema_from_uri(schema_uri)
  File "/opt/conda/lib/python3.8/site-packages/pystac/validation/stac_validator.py", line 150, in get_schema_from_uri
    s = json.loads(pystac.StacIO.default().read_text(schema_uri))
  File "/opt/conda/lib/python3.8/site-packages/pystac/stac_io.py", line 275, in read_text
    return self.read_text_from_href(href)
  File "/opt/conda/lib/python3.8/site-packages/pystac/stac_io.py", line 292, in read_text_from_href
    with urlopen(href) as f:
  File "/opt/conda/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/conda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
\' traceback=[\'  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 246, in run
    output = self.run_op_output_handler(content, run_id)
\', \'  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 278, in run_op_output_handler
    return self.run_op(content, run_id)
\', \'  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 273, in run_op
    raise RuntimeError("".join(ret.format()))
\']', status='failed')}

```

**Comment by renatolfc** [comment]
Hello @NicholasBerryman, we do validation of the STAC documents we create within FarmVibes.AI workflows.

It looks like your cluster isn't resolving names correctly. Can the host machine resolve "schemas.stacspec.org"?

What is the output of the command below?

```
~/.config/farmvibes-ai/kubectl exec -it deployment/terravibes-worker -- sh -c "pip install --user stac-validator ; /tmp/.local/bin/stac-validator https://raw.githubusercontent.com/stac-extensions/projection/main/examples/item.json"
```

If networking in your cluster is working OK, you should see output similar to

```
...

Thanks for using STAC version 1.0.0!

[
    {
        "version": "1.0.0",
        "path": "https://raw.githubusercontent.com/stac-extensions/projection/main/examples/item.json",
        "schema": [
            "https://stac-extensions.github.io/projection/v1.0.0/schema.json",
            "https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json"
        ],
        "valid_stac": true,
        "asset_type": "ITEM",
        "validation_method": "default"
    }
]
```

**Comment by NicholasBerryman** [comment]
Running that command gives another 'temporary failure in name resolution' (attached).

Interestingly, running a CURL to that url works fine from the host context. It seems it's just an issue with the cluster.

![image](https://user-images.githubusercontent.com/3523408/202596267-fe0ee930-95fe-4ecd-b7be-6eb099d0414e.png)

**Comment by renatolfc** [comment]
Seems to be an issue with docker networking. Do you have any custom firewall rules that might be interfering with the network?

Was the AML Compute Instance added to an existing virtual network with custom networking policies?

I'm spinning up an AML instance do some debugging...

**Comment by renatolfc** [comment]
@NicholasBerryman, what is the output of running `docker exec -it farmvibes-ai cat /etc/resolv.conf`? In the AML CI I just tested, I get

```
search az1hnem5gzcelllfkly3wu2y5g.xx.internal.cloudapp.net
nameserver 192.168.49.1
options ndots:0
```

Where `192.168.49.1` is the host VM's IP address.

What happens if you run `docker exec -it farmvibes-ai sh -c "echo nameserver 1.1.1.1 > /etc/resolv.conf"` to change the kubernetes cluster's host DNS to point to `1.1.1.1`?

Does STAC validation work now?

Does running `docker exec -it farmvibes-ai curl https://stacspec.org/` show any output now?

**Comment by NicholasBerryman** [comment]
Running `docker exec -it farmvibes-ai curl https://stacspec.org/` seems to work regardless of DNS server (`1.1.1.1` or `192.168.49.1`), but the [STAC validation command](https://github.com/microsoft/farmvibes-ai/issues/17#issuecomment-1319041668) produces the same error as [above](https://github.com/microsoft/farmvibes-ai/issues/17#issuecomment-1319436972) with both DNS servers.

The steps I followed in the setup look identical to yours.

I'll also have a chat to the relevant people in my organisation to see if there could be any firewall issues that I've not been made aware of.

**Comment by renatolfc** [comment]
We're working on an update to the images that will not run validation for catalogs created by us.

It'd be nice to know whether your firewall is blocking any types of outbound connections, though.

**Comment by renatolfc** [comment]
Hi @NicholasBerryman, were you able to chat with your network admins?

**Comment by NicholasBerryman** [comment]
Not yet, unfortunately. It's a bit of a busy time right now (harvest well is underway here), so it might take a little while.
I'll make sure to update this issue when I find out what firewall settings might've been interfering.

**Comment by renatolfc** [comment]
I was thinking about this for a while, what happens if you try to rewrite DNS requests from the containers?

Something like the following should work?

```
sudo iptables -t nat -A PREROUTING -p udp -d 8.8.8.8  --dport 53 -j DNAT --to <your DNS server IP>
```

---

If you are using `systemd-resolved`, you should be able to see your actual DNS server with `resolvectl status | grep Current DNS`. Otherwise, your DNS server should be listed on `/etc/resolv.conf`. On my system, I get this:

```
$ resolvectl status | grep "Current DNS"
  Current DNS Server: 168.63.129.16
```

So, on my system, that iptables line would read

```
sudo iptables -t nat -A PREROUTING -p udp -d 8.8.8.8  --dport 53 -j DNAT --to 168.63.129.16
```

**Comment by renatolfc** [comment]
BTW, we are changing our kubernetes implementation backend and we are implementing some DNS fixes that might help in cases such as this.

**Comment by NicholasBerryman** [comment]
Looks like some combination of the most recent updates here and some changes in my organisations firewall settings have solved this.
Thanks for helping troubleshoot!
Feel free to close this issue.
