### ISSUE TITLE
Incomptabile Version name for vibe_core/setup.py "2023-02-16" makes it fail for enviroments setup 

### ISSUE THREAD

**Issue by Amr-MKamal** [microsoft/farmvibes-ai#48]
in file farmvibes-ai/src/vibe_core/setup.py the version name "2023-02-16" is incompatible with older versions of pip which is used by the environments so the environment setup fails after  PEP 440 error , a quick solve was to locally change the version name to " 2023.2.16" which solved the problem for most environments , yet it's very apparent that different notebooks uses different package versions in their environments which makes them incompatible with each other & makes the API integration harder eventually I hope that wide compatibility gets a better focus in upcoming releases

**Comment by richstep** [comment]
I'm having the same issue which I believe is related.

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/home/azureuser/anaconda3/envs/farmvibes-ai/lib/python3.8/site-packages/setuptools/_normalization.py", line 62, in safe_version
          return str(packaging.version.Version(v))
        File "/home/azureuser/anaconda3/envs/farmvibes-ai/lib/python3.8/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __i
nit__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '2023-02-16'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/azureuser/farmvibes-ai/src/vibe_core/setup.py", line 3, in <module>
          setup(
        File "/home/azureuser/anaconda3/envs/farmvibes-ai/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/azureuser/anaconda3/envs/farmvibes-ai/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/azureuser/anaconda3/envs/farmvibes-ai/lib/python3.8/site-packages/setuptools/dist.py", line 483, in __init__
          self.patch_missing_pkg_info(attrs)
        File "/home/azureuser/anaconda3/envs/farmvibes-ai/lib/python3.8/site-packages/setuptools/dist.py", line 472, in patch_missing_pkg_info
          dist._version = _normalization.safe_version(str(attrs['version']))
        File "/home/azureuser/anaconda3/envs/farmvibes-ai/lib/python3.8/site-packages/setuptools/_normalization.py", line 65, in safe_version
          return str(packaging.version.Version(attempt))
        File "/home/azureuser/anaconda3/envs/farmvibes-ai/lib/python3.8/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __i
nit__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '2023-02-16'
      [end of output]

**Comment by renatolfc** [comment]
Thanks for reporting, folks. We are working on a fix in our pipelines.

**Comment by renatolfc** [comment]
For those with installation issues (@Amr-MKamal, @richstep) , does a `pip install --upgrade pip` fix the installation error?
