### ISSUE TITLE
Sentinel-2 Preprocess error - LocalResourceExists

### ISSUE THREAD

**Issue by NicholasBerryman** [microsoft/farmvibes-ai#50]
When running a Sentinel-2 workflow for:
* Coordinates: `121.3853 , -33.27323 , 121.5615 , -33.10911`
* Date range: `2022-1-1` to `2022-12-30`

I receive the following error:
```{'s2.s2.list': RunDetails(start_time=datetime.datetime(2023, 2, 22, 6, 1, 21, 133466), submission_time=datetime.datetime(2023, 2, 22, 6, 1, 21, 8694), end_time=datetime.datetime(2023, 2, 22, 6, 1, 21, 168646), reason=None, status='done'),
 's2.s2.filter': RunDetails(start_time=datetime.datetime(2023, 2, 22, 6, 1, 21, 353780), submission_time=datetime.datetime(2023, 2, 22, 6, 1, 21, 185469), end_time=datetime.datetime(2023, 2, 22, 6, 1, 21, 390884), reason=None, status='done'),
 's2.s2.download': RunDetails(start_time=datetime.datetime(2023, 2, 22, 6, 1, 21, 451478), submission_time=datetime.datetime(2023, 2, 22, 6, 1, 21, 409055), end_time=datetime.datetime(2023, 2, 22, 6, 1, 23, 447684), reason=None, status='done'),
 's2.s2.preprocess': RunDetails(start_time=datetime.datetime(2023, 2, 22, 6, 22, 30, 897563), submission_time=datetime.datetime(2023, 2, 22, 6, 1, 23, 464084), end_time=datetime.datetime(2023, 2, 22, 6, 39, 53, 205683), reason='RuntimeError: Received unsupported message header=MessageHeader(type=<MessageType.error: \'error\'>, run_id=UUID(\'2dcb7a30-af57-4950-8b95-9fd474f95ab2\'), id=\'00-2dcb7a30af5749508b959fd474f95ab2-3c83c6aaf8670721-01\', parent_id=\'00-2dcb7a30af5749508b959fd474f95ab2-1d50c297f4140322-01\', version=\'1.0\', created_at=datetime.datetime(2023, 2, 22, 6, 39, 53, 195758)) content=ErrorContent(status=<OpStatusType.failed: \'failed\'>, ename="<class \'RuntimeError\'>", evalue=\'Traceback (most recent call last):\
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 123, in run_op\
    return factory.build(spec).run(input, cache_info)\
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/ops.py", line 99, in run\
    items_out = self.storage.store(run_id, stac_results, cache_info)\
  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/storage/local_storage.py", line 135, in store\
    raise LocalResourceExistsError(\
vibe_agent.storage.local_storage.LocalResourceExistsError: Op output already exists in storage for stack_sentinel2_bands with id 4d21a03a-4bfe-42ce-9fe2-ab43a7fda690.\
\', traceback=[\'  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 309, in run_op_from_message\
    out = self.run_op_with_retry(content, message.run_id)\
\', \'  File "/opt/conda/lib/python3.8/site-packages/vibe_agent/worker.py", line 402, in run_op_with_retry\
    raise RuntimeError("".join(ret.format()))\
\']). Aborting execution.', status='failed')}```

**Comment by robertomest** [comment]
Hi @NicholasBerryman, I'm sorry you are still having problems running the workflows. I ran the `data_ingestion/sentinel2/preprocess_s2` workflow for your input and did not encounter any issues: the workflow ran to completion and returned 133 products with tile id '51HUD'. Can you verify what happens if you rerun the workflow (is this a recurring problem)? Is this on the same region where the assets were missing from the Planetary Computer in your previous issue?

**Comment by NicholasBerryman** [comment]
Thanks for the response. Most workflow's I've run seem to be fine, just a handful of issues here and there like this. I appreciate all the help!
This is a different location to the previous issue.
It the issue was recurrent yesterday even after restarting the cluster and again after deleting the cache and reinstalling the cluster, but it seems to have worked fine today. 
I'll reopen this if I see it happening reproducibly again.

**Comment by robertomest** [comment]
Thanks! Do keep us posted on any issues you come across.
