### ISSUE TITLE
BufferError while running ndvi_summary notebook

### ISSUE THREAD

**Issue by Shourya13** [microsoft/farmvibes-ai#66]
Following is the error we got while running the ndvi summary notebook along with the specifications of our VM
RAM : 32
Disk size : 2TB
Free space : 767.8 GB
vCPU : 8

[I 13:31:13.568 NotebookApp] Saving file at /land_degradation/land_degradation.ipynb
[E 14:17:02.094 NotebookApp] Exception in callback <bound method WebSocketMixin.send_ping of ZMQChannelsHandler(87d1348c-b134-473b-ab6b-570bfb826b7d)>
    Traceback (most recent call last):
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 921, in _run
        val = self.callback()
      File "/home/azureuser/.local/lib/python3.8/site-packages/notebook/base/zmqhandlers.py", line 188, in send_ping
        self.ping(b'')
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 445, in ping
        self.ws_connection.write_ping(data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 1101, in write_ping
        self._write_frame(True, 0x9, data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/iostream.py", line 540, in write
        self._write_buffer.append(data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/iostream.py", line 157, in append
        b += data  # type: ignore
    BufferError: Existing exports of data: object cannot be re-sized
[E 15:31:02.090 NotebookApp] Exception in callback <bound method WebSocketMixin.send_ping of ZMQChannelsHandler(87d1348c-b134-473b-ab6b-570bfb826b7d)>
    Traceback (most recent call last):
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 921, in _run
        val = self.callback()
      File "/home/azureuser/.local/lib/python3.8/site-packages/notebook/base/zmqhandlers.py", line 188, in send_ping
        self.ping(b'')
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 445, in ping
        self.ws_connection.write_ping(data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 1101, in write_ping
        self._write_frame(True, 0x9, data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/iostream.py", line 540, in write
        self._write_buffer.append(data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/iostream.py", line 157, in append
        b += data  # type: ignore
    BufferError: Existing exports of data: object cannot be re-sized
[E 16:12:32.092 NotebookApp] Exception in callback <bound method WebSocketMixin.send_ping of ZMQChannelsHandler(87d1348c-b134-473b-ab6b-570bfb826b7d)>
    Traceback (most recent call last):
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 921, in _run
        val = self.callback()
      File "/home/azureuser/.local/lib/python3.8/site-packages/notebook/base/zmqhandlers.py", line 188, in send_ping
        self.ping(b'')
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 445, in ping
        self.ws_connection.write_ping(data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 1101, in write_ping
        self._write_frame(True, 0x9, data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/iostream.py", line 540, in write
        self._write_buffer.append(data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/iostream.py", line 157, in append
        b += data  # type: ignore
    BufferError: Existing exports of data: object cannot be re-sized
[E 17:24:02.092 NotebookApp] Exception in callback <bound method WebSocketMixin.send_ping of ZMQChannelsHandler(87d1348c-b134-473b-ab6b-570bfb826b7d)>
    Traceback (most recent call last):
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 921, in _run
        val = self.callback()
      File "/home/azureuser/.local/lib/python3.8/site-packages/notebook/base/zmqhandlers.py", line 188, in send_ping
        self.ping(b'')
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 445, in ping
        self.ws_connection.write_ping(data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 1101, in write_ping
        self._write_frame(True, 0x9, data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/iostream.py", line 540, in write
        self._write_buffer.append(data)
      File "/home/azureuser/.local/lib/python3.8/site-packages/tornado/iostream.py", line 157, in append
        b += data  # type: ignore
    BufferError: Existing exports of data: object cannot be re-sized 

![Screenshot 2023-03-09 224004(1)](https://user-images.githubusercontent.com/27403023/224329801-d7b69da5-29c5-46a9-9333-0042ff7cc948.png)

This is where the execution has been stuck and the values are not updating anymore.

**Comment by py5gol** [comment]
Hi @Shourya13, thanks for using FarmVibes.AI - Could you please share the date range and area of interest? We will check this issue and get back to you soon. Thanks, Roberto

**Comment by Shourya13** [comment]
Hi @py5gol, thanks for the support. Following are the details : 
Date range : 01 Apr 2020 - 30 Dec 2020
Area of interest : -91.838525 42.603940, -91.838320 42.607137, -91.835413 42.607137, -91.835430 42.603931, -91.838525 42.603940

**Comment by Shourya13** [comment]
@py5gol
Update : After re-running the notebook, we got errors and everything has stopped updating.

![image](https://user-images.githubusercontent.com/27403023/224901870-47160e21-08c9-41f4-998a-87fee13b7d1c.png)

**Comment by py5gol** [comment]
Thanks for the update, @Shourya13. We have seen the problem with negative duration, and a fix will be released soon. I am investigating the issue using the parameters you shared above.

**Comment by py5gol** [comment]
Hi @Shourya13, I am sorry for the long delay. We release a new version of FarmVibes.AI two weeks ago. Could you update your instance and try it again? I am closing this issue for now, but feel free to reopen it if you are still having problems.
